# Generated by Django 4.0.6 on 2022-08-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunnybit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=5)),
                ('type', models.CharField(choices=[('RUN', 'Run'), ('SPECIAL', 'Special'), ('VERY_SPECIAL', 'Very Special'), ('BUNDERGROUND_STATION', 'Bunderground Station'), ('CARROT_SUPPLY', 'Carrot Supply'), ('CHINESE_ZODIAC', 'Chinese Zodiac'), ('DOLLA', 'Dolla'), ('METAL', 'Metal'), ('MYSTERIOUS_PLACE', 'Mysterious Place'), ('PLAY_IMMEDIATELY', 'Play Immediately'), ('RANK', 'Rank'), ('ROAMING_RED_RUN', 'Roaming Red'), ('ZODIAC', 'Zodiac')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pawns', models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('YELLOW', 'Yellow'), ('VIOLET', 'Violet'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BROWN', 'Brown')], max_length=255)),
                ('weapon_level', models.CharField(blank=True, max_length=255)),
                ('cabbage', models.IntegerField(blank=True, null=True)),
                ('radish', models.IntegerField(blank=True, null=True)),
                ('water', models.IntegerField(blank=True, null=True)),
                ('milk', models.IntegerField(blank=True, null=True)),
                ('psi', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(max_length=7)),
                ('poster', models.ImageField(blank=True, upload_to='decks')),
                ('cards', models.ManyToManyField(blank=True, to='killer_bunnies.card')),
            ],
        ),
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('D7', 'D7'), ('D10', 'D10'), ('D12', 'D12'), ('D20', 'D20'), ('ZODIAC', 'Zodiac'), ('CHINESE_ZODIAC', 'Chinese Zodiac')], max_length=255)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, upload_to='games')),
                ('decks', models.ManyToManyField(blank=True, to='killer_bunnies.deck')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='dice',
            field=models.ManyToManyField(blank=True, to='killer_bunnies.die'),
        ),
    ]
